### ISSUE TITLE
Issue in completying downloads

### ISSUE THREAD

**Issue by mchlprni** [mbikovitsky/panopto-m3u8#1]
I'm trying to download a video off Panopto. But with the url I've copied and youtube-dl I get the error "Unable to download webpage: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate"

How to solve?

**Comment by mbikovitsky** [comment]
Try this: https://stackoverflow.com/a/60158194/851560

**Comment by mchlprni** [comment]
I was able to download it but through another Chrome Extension. I’ve basically used yours to copy the links and then I pasted them in “Live Stream Downloader” and it worked. The video was not damaged either.

**Comment by mbikovitsky** [comment]
Glad it worked out!
